### ISSUE TITLE
Idea does not fully support created plugin icon

### ISSUE THREAD

**Issue by xnike** [Salomon88/GcViewerPlugin#10]
On page Settings -> Plugin -> GCViewer is all black, but should be colored:

```
ERROR: null
Enclosed Exception:
style.syntax.error.at [<unknown>, style, font-style:italic;font-variant:normal;font-weight:bold;font-stretch:normal;font-size:21.1667px;font-family:Calibri;-inkscape-font-specification:'Calibri, Bold Italic';font-variant-ligatures:normal;font-variant-caps:normal;font-variant-numeric:normal;font-variant-east-asian:normal;fill:#ec553f;fill-opacity:1;stroke:none;stroke-width:0.999972;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1;paint-order:normal, java.lang.NullPointerException]
org.w3c.dom.DOMException: style.syntax.error.at [<unknown>, style, font-style:normal;font-variant:normal;font-weight:bold;font-stretch:normal;font-size:31.0618px;font-family:Calibri;-inkscape-font-specification:'Calibri, Bold';font-variant-ligatures:normal;font-variant-caps:normal;font-variant-numeric:normal;font-variant-east-asian:normal;stroke-width:1.16482, java.lang.NullPointerException]
	at org.apache.batik.css.engine.CSSEngine.getCascadedStyleMap(CSSEngine.java:824)
	at org.apache.batik.css.engine.CSSEngine.getComputedStyle(CSSEngine.java:867)
	at org.apache.batik.bridge.CSSUtilities.getComputedStyle(CSSUtilities.java:81)
	at org.apache.batik.bridge.CSSUtilities.convertDisplay(CSSUtilities.java:564)
	at org.apache.batik.bridge.SVGTextElementBridge.fillAttributedStringBuffer(SVGTextElementBridge.java:876)
	at org.apache.batik.bridge.SVGTextElementBridge.fillAttributedStringBuffer(SVGTextElementBridge.java:930)
	at org.apache.batik.bridge.SVGTextElementBridge.buildAttributedString(SVGTextElementBridge.java:850)
	at org.apache.batik.bridge.SVGTextElementBridge.computeLaidoutText(SVGTextElementBridge.java:630)
	at org.apache.batik.bridge.SVGTextElementBridge.buildGraphicsNode(SVGTextElementBridge.java:286)
	at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(GVTBuilder.java:224)
	at org.apache.batik.bridge.GVTBuilder.buildComposite(GVTBuilder.java:171)
	at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(GVTBuilder.java:219)
	at org.apache.batik.bridge.GVTBuilder.buildComposite(GVTBuilder.java:171)
	at org.apache.batik.bridge.GVTBuilder.build(GVTBuilder.java:82)
	at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:193)
	at org.apache.batik.transcoder.image.ImageTranscoder.transcode(ImageTranscoder.java:92)
	at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(XMLAbstractTranscoder.java:142)
	at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:141)
	at com.intellij.ui.svg.MyTranscoder$Companion.createImage(MyTranscoder.kt:51)
	at com.intellij.ui.svg.MyTranscoder.createImage(MyTranscoder.kt)
	at com.intellij.util.SVGLoader.load(SVGLoader.java:143)
	at com.intellij.util.SVGLoader.loadHiDPI(SVGLoader.java:158)
	at com.intellij.ide.plugins.newui.HiDPIPluginLogoIcon.loadSVG(HiDPIPluginLogoIcon.java:133)
	at com.intellij.ide.plugins.newui.PluginLogo.loadFileIcon(PluginLogo.java:336)
	at com.intellij.ide.plugins.newui.PluginLogo.tryLoadIcon(PluginLogo.java:316)
	at com.intellij.ide.plugins.newui.PluginLogo.tryLoadJarIcons(PluginLogo.java:256)
	at com.intellij.ide.plugins.newui.PluginLogo.loadPluginIcons(PluginLogo.java:184)
	at com.intellij.ide.plugins.newui.PluginLogo.lambda$runLoadTask$2(PluginLogo.java:147)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:255)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
ERROR: null
Enclosed Exception:
style.syntax.error.at [<unknown>, style, font-style:normal;font-variant:normal;font-weight:bold;font-stretch:normal;font-size:31.0618px;font-family:Calibri;-inkscape-font-specification:'Calibri, Bold';font-variant-ligatures:normal;font-variant-caps:normal;font-variant-numeric:normal;font-variant-east-asian:normal;stroke-width:1.16482, java.lang.NullPointerException]
```

**Comment by xnike** [comment]
Created support ticket [IDEA-245735](https://youtrack.jetbrains.com/issue/IDEA-245735)
